kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-lease-keeper
subjects:
  - kind: ServiceAccount
    name: job-lease-keeper
roleRef:
  kind: Role
  name: job-lease-keeper
  apiGroup: rbac.authorization.k8s.io
