apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: job-lease-keeper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: job-lease-keeper
  template:
    metadata:
      labels:
        name: job-lease-keeper
    spec:
      serviceAccountName: job-lease-keeper
      containers:
       - name: job-lease-keeper
         image: kubesailmaker/job-lease-keeper:0.4
         command:
         - "/job-lease-keeper"
         imagePullPolicy: IfNotPresent
         env:
         - name: CONTROLLER_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.name
         - name: JOBS_NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
         - name: JOBS_SUCCESS_THRESHOLD_MINUTES
           value: "60"
         - name: JOBS_FAILURE_THRESHOLD_MINUTES
           value: "120"
         - name: CHECK_FREQUENCY_MINUTES
           value: "30"

