kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-lease-controller
subjects:
  - kind: ServiceAccount
    name: job-lease-controller
roleRef:
  kind: Role
  name: job-lease-controller
  apiGroup: rbac.authorization.k8s.io
