apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-1
spec:
  backoffLimit: 0
  template:
    metadata:
      name: busybox-1
      labels:
        app: busybox-1
      annotations:
        vault.hashicorp.com/agent-inject: "true"
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "echo done"
      restartPolicy: Never
