apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-4
spec:
  backoffLimit: 0
  template:
    metadata:
      name: busybox-4
      labels:
        app: busybox-4
      annotations:
        vault.hashicorp.com/agent-inject: "true"
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "sleep 1h"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 10m
              memory: 16Mi
      restartPolicy: Never

