apiVersion: v1
kind: Pod
metadata:
  name: busybox-2
spec:
    containers:
      - name: busybox
        image: busybox
        command:
          - "/bin/sh"
          - "-c"
          - "sleep 40"
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 10m
            memory: 16Mi
    restartPolicy: Never

